[package]
name = "processor"
version = "0.1.0"
authors = ["wooq <wooq@nhnnext.org>"]

[dependencies]
iron = "*"
time = "*"
router = "*"
bodyparser = "*"
persistent = "*"
rustc-serialize = "*"

[dependencies.interface]
path = "../components/interface"